name = "openmarket-api"
main = "src/index.ts"
compatibility_date = "2025-03-01"

[dev]
port = 8787

[vars]
ENVIRONMENT = "development"

[[d1_databases]]
binding = "DB"
database_name = "openmarket-db"
database_id = "f439c5b9-71ba-4038-a588-88c6adf61e32"
migrations_dir = "src/db/migrations"
